import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ChatProvider } from "@/lib/context/chat-context";
import Sidebar from "@/components/sidebar";
import SectionTitle from "@/components/sidebar-header"
import {
  Card,
  CardContent,
  CardHeader,
} from "@/components/ui/card"
import ChatTitle from "@/components/chat-header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Papel Chat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning suppressContentEditableWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ChatProvider>
            <div className="font-sans flex flex-row min-h-screen">
              <Sidebar />
              <Card className="w-full p-3 px-8 rounded-none border-none">
                {/* <CardHeader className="px-0">
                  <ChatTitle title="Welcome" />
                </CardHeader> */}
                <CardContent className={"space-y-2 max-h-[70vh] w-full overflow-y-auto px-0"}>
                  {children}
                </CardContent>
              </Card>
              {/* {children} */}
            </div>
          </ChatProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
