import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/theme-provider";
import { ChatProvider } from "@/lib/context/chat-context";
import { Toaster } from 'sonner'
import Sidebar from "@/components/sidebar";
import SectionTitle from "@/components/sidebar-header"
import {
  Card,
  CardContent,
  CardHeader,
} from "@/components/ui/card"
import ChatTitle from "@/components/chat-header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Papel Chat",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning suppressContentEditableWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <ChatProvider>
              <Toaster position="top-right" />
              {children}
            </ChatProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
